import type { Metadata } from 'next'
import { IBM_Plex_Sans } from 'next/font/google'
import './globals.css'

const ibm = IBM_Plex_Sans({  weight: ['200', '300', '400', '500', '600', '700'],
style: ['normal'],
subsets: ['latin'],
display: 'swap', });

export const metadata: Metadata = {
  title: 'AirSoft Studios',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibm.className}>{children}</body>
    </html>
  )
}
