"use client"
import { useEffect } from 'react';
import type { Metadata } from 'next';
import { IBM_Plex_Sans } from 'next/font/google';
import './globals.css';

const ibm = IBM_Plex_Sans({
  weight: ['200', '300', '400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: 'AirSoft Studios',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    // Tawk.to script
    const script = document.createElement('script');
    script.async = true;
    script.src='https://embed.tawk.to/60a653e8b1d5182476bacd45/1f64rfhuf';
    script.charset = 'UTF-8';
    script.setAttribute('crossorigin', '*');
    document.body.appendChild(script);

    const handleLoad = () => {
      if (window.Tawk_API) {
        console.log('Tawk API is ready');
      }
    };

    window.addEventListener('tawkLoad', handleLoad);

    return () => {
      document.body.removeChild(script);
      window.removeEventListener('tawkLoad', handleLoad);
    };
  }, []);

  return (
    <html lang="en">
      <body className={ibm.className}>
        <link rel="icon" href="/logoo.svg" sizes="any" />
        {children}
      </body>
    </html>
  );
}
